
-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Lab6_Optimised_simulink\ADFT.vhd
-- Created: 2025-11-01 15:12:32
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-06
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        1e-06
-- Out2                          ce_out        1e-06
-- Out3                          ce_out        1e-06
-- Out4                          ce_out        1e-06
-- Out5                          ce_out        1e-06
-- Out6                          ce_out        1e-06
-- Out7                          ce_out        1e-06
-- Out8                          ce_out        1e-06
-- Out9                          ce_out        1e-06
-- Out10                         ce_out        1e-06
-- Out11                         ce_out        1e-06
-- Out12                         ce_out        1e-06
-- Out13                         ce_out        1e-06
-- Out14                         ce_out        1e-06
-- Out15                         ce_out        1e-06
-- Out16                         ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ADFT
-- Source Path: Lab6_Optimised_simulink/ADFT
-- Hierarchy Level: 0
-- Model version: 10.9
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ADFT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In2                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In3                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In4                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In5                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In6                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In7                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In8                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In9                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In10                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In11                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In12                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In13                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In14                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In15                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        In16                              :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out2                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out3                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out4                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out5                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out6                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out7                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out8                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out9                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out10                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out11                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out12                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out13                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out14                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out15                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        Out16                             :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END ADFT;


ARCHITECTURE rtl OF ADFT IS

  -- Component Declarations
  COMPONENT alpha2_FFT1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT9
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT11
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          In2                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  COMPONENT alpha2_FFT24